export const environment = {
  production: true,
  clientId: '798a845b4f654799af7c74f3cc96f2f5',
  clientSecret: '01e02c93fad44d85ac0b081de4f63a58',
  redirectUri: 'http://localhost:4200/callback',
  apiConfig: 'https://api.spotify.com/v1',
  scope:
    'user-read-private user-read-email user-modify-playback-state user-read-currently-playing user-library-read playlist-modify-public playlist-modify-private user-top-read user-read-playback-state',
  state: '123',
  apiPaths: {
    mePlaylist: '/me/playlists ',
    picturePlaylist: (id: string) => `/playlists/${id}/images`,
    infoPlaylist: (id: string) => `/playlists/${id}`,
    getPlaylist: (id: string) => `/playlists/${id}/tracks`,
    topTrack: `/browse/featured-playlists`,
    getArtist: (id: string) => `/artists/${id}`,
    getTrackAlbum: (id: string) => `/albums/${id}/tracks`,
    getAlbumDetail: (id: string) => `/albums/${id}`,
    getNewAlbum: '/browse/new-releases',
    playMusic: '/me/player/play',
    pauseMusic: '/me/player/pause',
    currentPlay: '/me/player/currently-playing',
    getTrack: (id: string) => `/tracks/${id}`,
    getTrackArtist: (id: string) => `/artists/${id}/top-tracks`,
    getDevice: '/me/player/devices',
  },
};
